### ISSUE TITLE
Не корректная работа метода create() модели

### ISSUE THREAD

**Issue by max107** [studio107/Mindy#37]
product_id = fk до другой модели

``` php
Image::objects()->create([
    'product_id' => $item->id,
    'image' => new RemoteFile($imageUrl),
    'is_main' => $i == 0
]);
```

```
Mindy\Query\Exception\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'product_id' cannot be null
The SQL being executed was: INSERT INTO `catalog_image` (`product_id`, `image`, `is_main`, `position`) VALUES (NULL, 'Catalog/Image/2015-03-30/492a6ba4e68e9eb4da8e341cd5dc9be5_0.jpg', 1, 1) (/Volumes/mac/Users/max/projects/ko2/app/vendor/mindy/query/src/Mindy/Query/Schema.php:517)
#0 /Volumes/mac/Users/max/projects/ko2/app/vendor/mindy/query/src/Mindy/Query/Command.php(734): Mindy\Query\Schema->convertException(Object(PDOException), 'INSERT INTO `ca...')
#1 /Volumes/mac/Users/max/projects/ko2/app/vendor/mindy/orm/src/Mindy/Orm/Base.php(871): Mindy\Query\Command->execute()
#2 /Volumes/mac/Users/max/projects/ko2/app/vendor/mindy/orm/src/Mindy/Orm/Base.php(690): Mindy\Orm\Base->insertInternal(Array)
#3 /Volumes/mac/Users/max/projects/ko2/app/vendor/mindy/orm/src/Mindy/Orm/Base.php(639): Mindy\Orm\Base->insert(Array)
#4 /Volumes/mac/Users/max/projects/ko2/app/vendor/mindy/orm/src/Mindy/Orm/Manager.php(377): Mindy\Orm\Base->save()
#5 /Volumes/mac/Users/max/projects/ko2/app/Modules/Ko/Commands/KoMigrateCommand.php(50): Mindy\Orm\Manager->create(Array)
#6 [internal function]: Modules\Ko\Commands\KoMigrateCommand->actionIndex()
#7 /Volumes/mac/Users/max/projects/ko2/app/vendor/mindy/console/src/Mindy/Console/ConsoleCommand.php(213): ReflectionMethod->invokeArgs(Object(Modules\Ko\Commands\KoMigrateCommand), Array)
#8 /Volumes/mac/Users/max/projects/ko2/app/vendor/mindy/console/src/Mindy/Console/ConsoleCommandRunner.php(92): Mindy\Console\ConsoleCommand->run(Array)
#9 /Volumes/mac/Users/max/projects/ko2/app/vendor/mindy/application/src/Mindy/Application/Application.php(66): Mindy\Console\ConsoleCommandRunner->run(Array)
#10 /Volumes/mac/Users/max/projects/ko2/app/vendor/mindy/application/src/Mindy/Application/BaseApplication.php(539): Mindy\Application\Application->processRequest()
#11 /Volumes/mac/Users/max/projects/ko2/www/index.php(26): Mindy\Application\BaseApplication->run()
#12 {main}
```

**Comment by max107** [comment]
Идентичное поведение

```php
Image::objects()->create([
    'product' => $model,
    ...
]);
```
